ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'

urlpatterns = 	[
	path('', views.index),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = 	[
	path('', views.landing, name='landingPage'),
]

infoku/urls.py
from django.urls import path
from . import views

app_name = 'infoku'

urlpatterns = 	[
	path('', views.landing),
]

lab6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('info/', include('infoku.urls')),
    path('books/', include('ajax.urls')),
    path('story9/', include('story9.urls')),
]

story9/urls.py
from django.urls import path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
]

ajax/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
	isi = models.CharField(max_length=300)
	tanggal = models.DateTimeField(default=timezone.now)

# Create your models here.

infoku/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from . import models
from django import forms
import datetime

class StatusForm(forms.ModelForm):
    isi = forms.CharField(widget=forms.Textarea(attrs={
                "required" : True,
                "placeholder":"Apa yang ada dalam pikiranmu..",
                }))
  
   
    class Meta:
        model = models.Status
        fields = ["isi"]

ajax/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'index.html')

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status


# Create your views here.
def landing(request):
	if request.method =="POST":
		form = StatusForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('homepage:landingPage')
	else:
		form = StatusForm() 

	status = Status.objects.order_by("tanggal")
	listStatus = {
		'form' : form,
		'status' : status,
	}
	return render(request, "home.html", listStatus)

infoku/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
	return render(request, 'info.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as login_auth, logout as logout_auth

def index(request):
    user = request.user
    if user.is_authenticated:
        return render(request, 'sukses.html')        
    else:
        return redirect('story9:login')

def login(request):
    user = request.user
    login_form = AuthenticationForm()
    
    if user.is_authenticated:
        return redirect('story9:index')

    if request.method == "POST":
        login_form = AuthenticationForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login_auth(request, user)
            return redirect('story9:index')
    return render(request, 'login.html', {'form':login_form})

def logout(request):
    if request.method == 'POST':
        logout_auth(request)
    return redirect('story9:index')

ajax/templates/index.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/story8.css' %}" />
  
    <title>
            Cari Buku
    </title>
</head>

<body>

<div class="container">
    <div class="d-flex justify-content-center">
    <h1 style="font-family:Muli"> <b> BookFinder<b> </h1> 
    </div>

    <div class="d-flex justify-content-center">
    <form id="book-form" style="width:500px">

    <div class="row justify-content-md-center">
    <div class="col col-md-8">
    <input type="text" id="book-search" class="form-control form-control-lg" placeholder="Search book by title"> 
    </div>

    <div class="col col-lg-2">
    <button type="submit" class="btn btn-block btn-lg btn-success" id="b1" style="width:100px;">Find</button>
    </div>
    </div>

    </form>
    </div>

</div>


<div class="row justify-content-md-center" id="result">

</div>


<script src="{% static 'js/story8.js' %}"> </script>
</body>

</html>

homepage/templates/home.html
<!DOCTYPE html>
<html>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>

$(document).ready(function(){
  $("#b1").click(function(){ //pink button
    if(document.getElementById("b1").name == "0"){
    $("#layout").css({"background-color": "#f7eaf4"});
    $("html").css({"background-color": "#f7eaf4"});
    $("#n1").css({"background-color": "#e4268d"});
    $("#b1").css({"background-color": "#fa1958", "border-color" : "#e6aec1"});
    $("#col-1").css({"border-color" : "#f7cadf"});
    $("#col-2").css({"border-color" : "#f7cadf"});
    document.getElementById("b1").name = "1";
        }
else{
    $("#layout").css({"background-color": "#41b8c8"});
    $("html").css({"background-color": "#41b8c8"});
    $("#n1").css({"background-color": "#1c1d24"});
    $("#b1").css({"background-color": "#08acc3", "border-color" : "#17a2b8"});
    $("#col-1").css({"border-color" : "#0eb3c5"});
    $("#col-2").css({"border-color" : "#0eb3c5"});
    document.getElementById("b1").name = "0";

}

  });
});

</script>



<title> Story 6 - Update Status
    </title>
<style>
html{
    background-color:#41b8c8 ;
}
nav{
    background-color:#1c1d24;
}
body{
    background-color:#41b8c8;
}
#layout{
    padding:30px;
}
.col-sm{
    padding:25px;
    margin-left:50px;
    border:3px double #0eb3c5;
}
.button{
    margin-top:15px;
}
a{
    font-family:'Playfair Display'; 
}

</style>


</head>

<body>  
<nav class="navbar navbar-expand-lg navbar-light" id="n1">
  <a style="color:white;"class="navbar-brand" href="#"> PPW Story 6 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    </div>
  </div>
</nav>


<div class="container-fluid" id="layout">
     <button type="button" class="btn btn-info" id="b1" style="background-color:#08acc3;"   
    name="0" > Ganti tema </button>


  <div class="row">
    <div class="col-sm" style="margin-right:50px;background-color:white;max-height:480px;max-width:400px;margin-bottomZ:100px" id="col-1">
        <h1 style="line-height:1.5"> Status </h1> 
        <form method="POST" class="form"> 
    {% csrf_token %} 

    {{ form.isi }}


        <br/>
        <input type="submit" class="button" name="post" value="Submit" /> 
        </form>

    </div>

    <div class="col-sm"  style="background-color:white;max-width:700px" id="col-2">
                <h1> Timeline </h1>
                <p > </p>

                {% for stat in status %}
                <p style="border-style:groove;line-height:2">
                {{ stat.isi }}

                <br/>

                - 
                {{ stat.tanggal }}
                            <br/>
                </p>

                        <br/>
                {% endfor %}
    </div>

  </div>
</div>
  



</body>
</html>

infoku/templates/info.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Abhaya+Libre&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/story7.css' %}">
    <script src="{% static 'js/story7.js' %}"></script>



<style>

</style>
</head>

<body>

<div class="container" id="head">
<button type="button" class="btn btn-link" id="switch" name="0"> Ganti Tema </button>
</div>


<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto" id="div_1">
      <h1> Click the accordion to find out <br/> about me</h1>
    </div>
  </div>
  <div class="row justify-content-md-center">


    	
    	<div id="accordion">
        	<h3>Activity</h3>
        	<div style="background-color:rgba(3, 142, 169, 0.5);" id="p">
            <p>- Eat</p>
            <p>- Sleep</p>
            <p>- Ga gemuk gemuk :(</p>
        	</div>
        <h3>Experience</h3>
        	<div style="background-color:rgba(3, 142, 169, 0.5);" id="p">
            <p>- Wisuda Genap 2019</p>
            <p>- Staff Recis Moederland 2017</p>
            <p>- Panitia HUT-RI GKC 2019  </p>
        	</div>
        	<h3>Achievement</h3>
        	<div style="background-color:rgba(3, 142, 169, 0.5);" id="p">
            <p>- 2nd Place at Recis Stardust Cup Dota 2</p>
            <p>- Juara balap karung tingkat RT</p>
            <p>- Juara apalagi ya</p>
        	</div>
    	</div>



  
  </div>
</div>


</body>



</html>

story9/templates/login.html
<!DOCTYPE html>

<html>

<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<title>Story 9 | Login </title>
</head>
<div class="form">
        <center><h2 style="padding-top:5px;background-color:green;height:50px;color:white">Please login</h2></center>
        <form action="{% url 'story9:login' %}" method="POST" class="test mid" style="color:black">
            {% csrf_token %}


        	<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col">
      <p style="margin-right:30px">Username</p> 
            {{ form.username }}
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row">
    <div class="col">
    
    </div>
    <div class="col">
      <p style="margin-right:30px">Password</p> 
            {{ form.password }}
    </div>
    <div class="col">
   
    </div>
  </div>
   <div class="row">
    <div class="col">
    
    </div>
    <div class="col" style="margin-top:10px">
      <button type="submit" class="formbutton">Login</button>
    </div>
    <div class="col">
   
    </div>
  </div>
</div>
        </form>
    </div>


</html>

story9/templates/sukses.html
<!DOCTYPE html>

<html>
<head>
<title>Welcome to | Story 9 </title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<div class="form">
<center><h2 style="padding-top:5px;background-color:green;height:50px;color:white">Welcome</h2></center>
</div>

<div class="container">
<h3> Hello {{ user.username }}</h3>

<p> Selamat ! <br> Anda berhasil login ^^ <br> Have a nice day !</p>

 <form action="{% url 'story9:logout' %}" method="POST" class="test mid">
            {% csrf_token %}
            <div>
                <button type="submit" class="formbutton">Logout</button>
            </div>
    </form>
</div>	

</html>